### ISSUE TITLE
Availability of the data and models

### ISSUE THREAD

**Issue by maculjak** [Yuanhy1997/PartialKB-EL#1]
Thanks for your great work on Partial KB Inference in Biomedical EL!
It seems that the resources shared via a Google Drive link are not public. Can you make them public?
Also, are you planning on releasing the model weights?

**Comment by Yuanhy1997** [comment]
I will check the Google Drive link tomorrow. The Google Link contains the model weights and data for EntQA models. For other NER, NED and generative models, please refer to the data and model repos provided in this repo or in the paper. These models can be easily trained with one 3090 GPU.

**Comment by akhilarora** [comment]
@Yuanhy1997 is there any updates on the Google drive link: https://drive.google.com/drive/folders/0ADcHGax5A4G7Uk9PVA? The directory is still not publicly accessible. It would be great if you can change the visibility. Thanks. Wishing you a great weekend!

**Comment by Yuanhy1997** [comment]
Oh sorry, almost forgot. I just verified that the link is open accessible. But I will also past the link for the three specific contents here and see whether you can download:

https://drive.google.com/file/d/1aNycLPGt1tL1og0I_hD5DjdggJ73rKN1/view?usp=drive_link  -- The EntQA-Style MedMention Data,
https://drive.google.com/file/d/1xz_4KVtCskkQZgDI8rQB4qbxZ6JGHNrG/view?usp=drive_link -- Checkpoints for EntQA on Benchmarks,
https://drive.google.com/file/d/1fPk7kRdKvIRezVf8HAEje_j7jiyOQ7qg/view?usp=drive_link -- The EntQA-Style BC5CDR Data.

Really hope these would help!

**Comment by maculjak** [comment]
@Yuanhy1997 This is great, thanks for your help! It seems that the three links that you shared contain everything needed to reproduce EntQA results and use the model for inference. However, I still cannot access the original Google Drive link (https://drive.google.com/drive/folders/0ADcHGax5A4G7Uk9PVA). The landing page looks like the image below:
![image](https://github.com/Yuanhy1997/PartialKB-EL/assets/44749395/ba1c855d-4276-4c2c-bbe5-20db4a487cba)
Can you maybe set the sharing option of the directory with the data to _Anyone with the link_?
All the best!

**Comment by Yuanhy1997** [comment]
It is great that you can access the three links. I do not know where it goes wrong. We do set the access to anyone who knows the link. Anyway, I would put the three links to the readme and those are all what contains in theold link.

**Comment by maculjak** [comment]
Sounds good, I will close the issue then. Thanks once again for your help!
